name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build and Test
        run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO

